site_name: CANARI Sprint 
site_dir: public
nav:
  - 'docs/index.md'
  - 'docs/highlights.md'
  - 'docs/data.md'
  - 'docs/setup.md'
  - 'docs/sprint.md'
  - 'docs/tutorials.md'
  - 'docs/FAQ.md'
plugins:
  - search
  - print-site
markdown_extensions:
  - attr_list
