site_name: CANARI Sprint 
site_dir: public
doc:
  - 'index.md'
  - 'highlights.md'
  - 'data.md'
  - 'setup.md'
  - 'sprint.md'
  - 'tutorials.md'
  - 'FAQ.md'
nav:
  - 'index.md'
  - 'highlights.md'
  - 'data.md'
  - 'setup.md'
  - 'sprint.md'
  - 'tutorials.md'
  - 'FAQ.md'
plugins:
  - search
  - print-site
markdown_extensions:
  - attr_list
